# Generated by Django 3.2 on 2021-04-15 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangId', models.CharField(max_length=20, unique=True, verbose_name='ID Barang')),
                ('kode_barang', models.CharField(max_length=20, verbose_name='Kode Barang')),
                ('nama_barang', models.CharField(max_length=20, verbose_name='Nama Barang')),
                ('merk', models.CharField(max_length=20, verbose_name='Merk Barang')),
                ('stock', models.IntegerField(verbose_name='Stock Barang')),
                ('BAST_perolehan', models.FileField(default=None, upload_to='', verbose_name='BAST Perolehan')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_nrk', models.CharField(max_length=120, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('alamat', models.CharField(max_length=120)),
                ('telp', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangId', models.CharField(max_length=20, unique=True, verbose_name='ID Barang')),
                ('nomor_peminjaman', models.CharField(max_length=20, unique=True, verbose_name='Nomor Peminjaman')),
                ('nip_nrk', models.CharField(max_length=120, unique=True)),
                ('tgl_pinjam', models.DateField(default=datetime.date.today, help_text='Masukkan Tanggal Peminjaman', verbose_name='Tanggal Peminjaman')),
                ('tgl_kembali', models.DateField(help_text='Masukkan Tanggal Pengembalian', null=True, verbose_name='Tanggal Pengembalian')),
                ('BAST_disposisi', models.FileField(default=None, upload_to='', verbose_name='BAST Diposisi')),
            ],
        ),
    ]
