# Generated by Django 3.2 on 2021-04-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='nip_nrk',
        ),
    ]
