# Generated by Django 3.2 on 2021-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_remove_peminjaman_nip_nrk'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='nip_nrk',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
