# Generated by Django 3.2 on 2021-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0003_peminjaman_nip_nrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='nip_nrk',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
