# Generated by Django 3.2 on 2021-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nip_nrk', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='NIP/NIK')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('nama_pegawai', models.CharField(max_length=120, verbose_name='Nama')),
                ('alamat', models.CharField(max_length=120, verbose_name='Alamat')),
                ('telp', models.CharField(max_length=120, verbose_name='No. Telp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Activated')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
