# Generated by Django 3.2 on 2021-04-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='nama_pegawai',
            new_name='nama',
        ),
    ]
