# Generated by Django 3.2 on 2021-04-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_rename_nama_pegawai_useraccounts_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='nama',
            new_name='nama_pegawai',
        ),
    ]
