# Generated by Django 3.2 on 2021-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_rename_nama_useraccounts_nama_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='nama_pegawai',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nama'),
        ),
    ]
