# Generated by Django 3.2 on 2021-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_alter_useraccounts_nama_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='nip_nrk',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='NIP/NRK'),
        ),
    ]
