# Generated by Django 3.2 on 2021-04-22 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_nrk', models.CharField(max_length=120, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('alamat', models.CharField(max_length=120)),
                ('telp', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabelBarang',
            fields=[
                ('barangId', models.CharField(max_length=20, verbose_name='ID Barang')),
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Kode Barang')),
                ('nama_barang', models.CharField(max_length=20, unique=True, verbose_name='Nama Barang')),
                ('merk', models.CharField(max_length=20, verbose_name='Merk Barang')),
                ('stock', models.IntegerField(verbose_name='Stock Barang')),
                ('BAST_perolehan', models.FileField(default=None, upload_to='', verbose_name='BAST Perolehan')),
            ],
        ),
        migrations.CreateModel(
            name='TabelGedung',
            fields=[
                ('gedungID', models.CharField(default=None, max_length=10, verbose_name='ID Gedung')),
                ('gedung', models.CharField(default=None, max_length=8, primary_key=True, serialize=False, verbose_name='Gedung')),
                ('mg_gedung', models.CharField(default=None, max_length=120, verbose_name='MG Gedung')),
            ],
        ),
        migrations.CreateModel(
            name='TabelRuang',
            fields=[
                ('ruangID', models.CharField(default=None, max_length=10, verbose_name='ID Ruang')),
                ('ruang', models.CharField(default=None, max_length=8, primary_key=True, serialize=False, verbose_name='Ruang')),
                ('pj_ruang', models.CharField(default=None, max_length=120, verbose_name='PJ Ruang')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelgedung', verbose_name='Gedung')),
            ],
        ),
        migrations.CreateModel(
            name='TabelPeminjaman',
            fields=[
                ('id_Peminjaman', models.CharField(default=None, max_length=10, verbose_name='ID Peminjaman')),
                ('nomor_peminjaman', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='Nomor Peminjaman')),
                ('nama_pegawai', models.CharField(default=None, max_length=120, verbose_name='Nama Pegawai')),
                ('tgl_pinjam', models.DateField(default=datetime.date.today, help_text='Masukkan Tanggal Peminjaman', verbose_name='Tanggal Peminjaman')),
                ('tgl_kembali', models.DateField(help_text='Masukkan Tanggal Pengembalian', null=True, verbose_name='Tanggal Pengembalian')),
                ('BAST_disposisi', models.FileField(default=None, upload_to='', verbose_name='BAST Diposisi')),
                ('nip_nrk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NIP/NRK')),
            ],
        ),
        migrations.CreateModel(
            name='PeminjamanDetail',
            fields=[
                ('peminjamanID', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='ID Peminjaman')),
                ('jumlah', models.IntegerField(verbose_name='Jumlah Peminjaman')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelgedung', verbose_name='Gedung')),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_barang+', to='inventaris.tabelbarang', verbose_name='Kode Barang')),
                ('nama_barang', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nama_barang+', to='inventaris.tabelbarang', to_field='nama_barang', verbose_name='Nama Barang')),
                ('nomor_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelpeminjaman', verbose_name='Nomor Peminjaman')),
                ('ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelruang', verbose_name='Ruang')),
            ],
        ),
    ]
