# Generated by Django 3.2 on 2021-04-17 04:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('barangId', models.CharField(max_length=20, verbose_name='ID Barang')),
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Kode Barang')),
                ('nama_barang', models.CharField(max_length=20, verbose_name='Nama Barang')),
                ('merk', models.CharField(max_length=20, verbose_name='Merk Barang')),
                ('stock', models.IntegerField(verbose_name='Stock Barang')),
                ('BAST_perolehan', models.FileField(default=None, upload_to='', verbose_name='BAST Perolehan')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_nrk', models.CharField(max_length=120, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('alamat', models.CharField(max_length=120)),
                ('telp', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=120, verbose_name='Nama')),
                ('tgl_pinjam', models.DateField(default=datetime.date.today, help_text='Masukkan Tanggal Peminjaman', verbose_name='Tanggal Peminjaman')),
                ('tgl_kembali', models.DateField(help_text='Masukkan Tanggal Pengembalian', null=True, verbose_name='Tanggal Pengembalian')),
                ('BAST_disposisi', models.FileField(default=None, upload_to='', verbose_name='BAST Diposisi')),
                ('barangId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang', verbose_name='ID Barang')),
                ('nip_nrk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NIP/NRK')),
                ('nomor_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.pinjaman', verbose_name='Nomor Peminjaman')),
            ],
        ),
    ]
