# Generated by Django 3.2 on 2021-04-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='nama',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='nama_pegawai',
            field=models.CharField(default=None, max_length=120, verbose_name='Nama Pegawai'),
        ),
    ]
