# Generated by Django 3.2 on 2021-05-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_alter_peminjamandetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetail',
            name='status',
            field=models.CharField(choices=[('RS', 'Rusak'), ('PD', 'Pending'), ('BK', 'Baik')], default='PD', max_length=2, null=True),
        ),
    ]
