# Generated by Django 3.2 on 2021-04-17 08:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaris', '0002_auto_20210417_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanDetail',
            fields=[
                ('peminjamanID', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='ID Peminjaman')),
                ('jumlah', models.IntegerField(verbose_name='Jumlah Peminjaman')),
            ],
        ),
        migrations.CreateModel(
            name='TabelGedung',
            fields=[
                ('gedungID', models.CharField(default=None, max_length=10, verbose_name='ID Gedung')),
                ('gedung', models.CharField(default=None, max_length=8, primary_key=True, serialize=False, verbose_name='Gedung')),
                ('mg_gedung', models.CharField(default=None, max_length=120, verbose_name='MG Gedung')),
            ],
        ),
        migrations.CreateModel(
            name='TabelPeminjaman',
            fields=[
                ('id_Peminjaman', models.CharField(default=None, max_length=10, verbose_name='ID Peminjaman')),
                ('nomor_peminjaman', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='Nomor Peminjaman')),
                ('nama_pegawai', models.CharField(default=None, max_length=120, verbose_name='Nama Pegawai')),
                ('tgl_pinjam', models.DateField(default=datetime.date.today, help_text='Masukkan Tanggal Peminjaman', verbose_name='Tanggal Peminjaman')),
                ('tgl_kembali', models.DateField(help_text='Masukkan Tanggal Pengembalian', null=True, verbose_name='Tanggal Pengembalian')),
                ('BAST_disposisi', models.FileField(default=None, upload_to='', verbose_name='BAST Diposisi')),
                ('nip_nrk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NIP/NRK')),
            ],
        ),
        migrations.CreateModel(
            name='TabelRuang',
            fields=[
                ('ruangID', models.CharField(default=None, max_length=10, verbose_name='ID Ruang')),
                ('ruang', models.CharField(default=None, max_length=8, primary_key=True, serialize=False, verbose_name='Ruang')),
                ('pj_ruang', models.CharField(default=None, max_length=120, verbose_name='MG Gedung')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelgedung', verbose_name='Gedung')),
            ],
        ),
        migrations.RenameModel(
            old_name='Barang',
            new_name='TabelBarang',
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
        migrations.DeleteModel(
            name='Pinjaman',
        ),
        migrations.AddField(
            model_name='peminjamandetail',
            name='gedung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelgedung', verbose_name='Gedung'),
        ),
        migrations.AddField(
            model_name='peminjamandetail',
            name='kode_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelbarang', verbose_name='Kode Barang'),
        ),
        migrations.AddField(
            model_name='peminjamandetail',
            name='nomor_peminjaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelpeminjaman', verbose_name='Nomor Peminjaman'),
        ),
        migrations.AddField(
            model_name='peminjamandetail',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelruang', verbose_name='Ruang'),
        ),
    ]
