# Generated by Django 3.2 on 2021-04-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaris', '0003_auto_20210417_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelpeminjaman',
            name='nip_nrk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NIP/NRK'),
        ),
        migrations.AlterField(
            model_name='tabelruang',
            name='pj_ruang',
            field=models.CharField(default=None, max_length=120, verbose_name='PJ Ruang'),
        ),
    ]
