# Generated by Django 3.2 on 2021-05-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0005_rename_status_peminjamandetail_kodnisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjamandetail',
            old_name='kodnisi',
            new_name='kondisi',
        ),
    ]
