# Generated by Django 3.2 on 2021-04-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0005_alter_peminjamandetail_nama_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetail',
            name='kode_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelbarang', verbose_name='Kode Barang'),
        ),
    ]
