# Generated by Django 3.2 on 2021-05-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0006_rename_kodnisi_peminjamandetail_kondisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjamandetail',
            old_name='kembali',
            new_name='status',
        ),
    ]
