# Generated by Django 3.2 on 2021-04-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0008_auto_20210422_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamandetail',
            name='nama_barang',
        ),
    ]
