# Generated by Django 3.2 on 2021-04-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0009_remove_peminjamandetail_nama_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamandetail',
            name='kode_barang',
        ),
    ]
