# Generated by Django 3.2 on 2021-04-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0010_remove_peminjamandetail_kode_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamandetail',
            name='kode_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventaris.tabelbarang', verbose_name='Kode Barang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjamandetail',
            name='nama_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nama_barang+', to='inventaris.tabelbarang', to_field='nama_barang', verbose_name='Nama Barang'),
        ),
    ]
