# Generated by Django 3.2 on 2021-04-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0011_auto_20210422_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetail',
            name='nama_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nama_barang+', to='inventaris.tabelbarang', to_field='nama_barang', verbose_name='Nama Barang'),
            preserve_default=False,
        ),
    ]
