# Generated by Django 3.2 on 2021-04-23 07:58

from django.db import migrations, models
import inventaris.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0012_alter_peminjamandetail_nama_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetail',
            name='peminjamanID',
            field=models.CharField(default=inventaris.models.PeminjamanDetail.getTotalCount, max_length=10, primary_key=True, serialize=False, verbose_name='ID Peminjaman'),
        ),
        migrations.AlterField(
            model_name='tabelbarang',
            name='barangId',
            field=models.CharField(default=inventaris.models.TabelBarang.getTotalCount, max_length=20, verbose_name='ID Barang'),
        ),
        migrations.AlterField(
            model_name='tabelgedung',
            name='gedungID',
            field=models.CharField(default=inventaris.models.TabelGedung.getTotalCount, max_length=10, verbose_name='ID Gedung'),
        ),
        migrations.AlterField(
            model_name='tabelpeminjaman',
            name='id_Peminjaman',
            field=models.CharField(default=inventaris.models.TabelPeminjaman.getTotalCount, max_length=10, verbose_name='ID Peminjaman'),
        ),
        migrations.AlterField(
            model_name='tabelpeminjaman',
            name='nomor_peminjaman',
            field=models.CharField(default=inventaris.models.TabelPeminjaman.getNomor, max_length=10, primary_key=True, serialize=False, verbose_name='Nomor Peminjaman'),
        ),
        migrations.AlterField(
            model_name='tabelruang',
            name='ruangID',
            field=models.CharField(default=inventaris.models.TabelRuang.getTotalCount, max_length=10, verbose_name='ID Ruang'),
        ),
    ]
