# Generated by Django 3.2 on 2021-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0013_auto_20210423_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelbarang',
            name='kode_barang',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Kode Barang'),
        ),
    ]
