# Generated by Django 3.2 on 2021-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0016_auto_20210427_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelbarang',
            name='BAST_perolehan',
            field=models.FileField(default=None, upload_to='Documents/Perolehan/', verbose_name='BAST Perolehan'),
        ),
        migrations.AlterField(
            model_name='tabelpeminjaman',
            name='BAST_disposisi',
            field=models.FileField(default=None, upload_to='Documents/Disposisi/', verbose_name='BAST Diposisi'),
        ),
    ]
