# Generated by Django 3.2 on 2021-05-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0017_auto_20210427_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelbarang',
            name='BAST_perolehan',
            field=models.URLField(default=None, verbose_name='BAST Perolehan'),
        ),
        migrations.AlterField(
            model_name='tabelpeminjaman',
            name='BAST_disposisi',
            field=models.URLField(default=None, verbose_name='BAST Diposisi'),
        ),
    ]
